name: Build and release container image

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile latex
        uses: xu-cheng/latex-action@v3
        with:
          pre_compile: |
            shopt -s extglob
          root_file: |
            documenti/*.tex
            document/*/!(*esterno*).tex
      - name: Append version to files
        run: |
          for file in documenti/*.tex
          do
          VERSION_NUMBER="$(grep '\\providecommand{\\versionnumber}' $file | sed 's/.*{\([^{]*\)}$/\1/')"
          BASE_NAME="$(basename "$file")"
          NAME="${BASE_NAME%.tex}"
          mv -- "$NAME".pdf "$NAME-v$VERSION_NUMBER".pdf
          done
      - name: Setup Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git fetch --all
      - name: Publish
        run: |
          git add *.pdf
          git stash
          git switch gh-pages
          git rm *.pdf || echo "No pdf files found"
          git stash pop
          git checkout stash -- *.pdf || echo "No pdf files found"
          git add *.pdf
          git commit -m "Upload pdf build"
          git push origin
        
