on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - master

permissions:
  checks: write
  contents: read
jobs:
  run-aspell:
    name: Run aspell
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Run aspell
        run: |
           aspell/aspell.py documenti/*.tex > annotations.json
      - name: Annotate PR
        uses: yuzutech/annotations-action@v0.4.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          title: 'lint'
          input: './annotations.json'

        
